name: actions wf
on: pull_request
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Title
          body: Body
          assignees: "hierodula"
      - uses: |
          echo ${{steps.issue.outputs.issue}}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "anybody here"
      - run: echo "Time ${{steps.hello.outputs.time}}"
