name: actions wf
on: pull_request
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: npm ci
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: 'anybody here'
      - run: echo "Time ${{steps.hello.output.time}}"